name: CI-CD-vot-eto-vot

# Run
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  #  Manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: BPR2Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: dockerfile
          docker_options: "--no-cache"
          process_type: web # https://devcenter.heroku.com/articles/process-model
