name: CI-CD-vot-eto-vot

# Run
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  #  Manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: BPR2Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: itskoshkin@icloud.com
          heroku_api_key: 9e95ede0-1c9d-4a2c-899d-a5a3e2c5dff4
          heroku_app_name: party-ping-bot
          dockerfile_directory: ./
          dockerfile_name: dockerfile
          docker_options: "--no-cache"
          process_type: web # https://devcenter.heroku.com/articles/process-model
