name: CI-CD-vot-eto-vot

# Run
on:
  push:
    branches: [ "master" ]
  #  Manually
  workflow_dispatch:

jobs: 
  telegram-start:
    runs-on: ubuntu-latest
    environment: Main
    steps:
      - name: notify in telega about start
        uses: appleboy/telegram-action@master
        with:
            to: ${{secrets.TELEGRAM_TO}}
            token: ${{secrets.TELEGRAM_TOKEN}}
            disable_web_page_preview: true
            format: markdown
            message: |
              [${{github.actor}}](https://github.com/${{github.actor}}) made a commit «${{github.event.commits[0].message}}» in [${{github.repository}}](https://github.com/${{github.repository}}), starting `Actions`...

  docker:
    runs-on: ubuntu-latest
    environment: Main
    needs: telegram-start
    steps:
      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_ACCESSTOKEN}}
      - name: Build
        run: docker image build -t itskoshkin/party-ping-bot:0.1 .
      - name: Push
        run: docker push itskoshkin/party-ping-bot:0.1

  heroku:
    runs-on: ubuntu-latest
    environment: Main
    needs: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: deploy 2 Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{secrets.HERO_EMAIL}}
          heroku_api_key: ${{secrets.HERO_APIKEY}}
          heroku_app_name: ${{secrets.HERO_APPNAME}}
          dockerfile_directory: ./
          dockerfile_name: dockerfile
          docker_options: "--no-cache"
          process_type: worker

  telegram-finish:
    runs-on: ubuntu-latest
    environment: Main
    needs: heroku
    if: always() && needs.heroku.result == 'success'
    steps:
      - name: notify in telega about finish
        uses: appleboy/telegram-action@master
        with:
            to: ${{secrets.TELEGRAM_TO}}
            token: ${{secrets.TELEGRAM_TOKEN}}
            disable_web_page_preview: true
            format: markdown
            message: |
              `Heroku Job Success`
              
              [It just works](https://party-ping-bot.herokuapp.com)
                  — Todd Hovard

  telegram-fail:
    runs-on: ubuntu-latest
    environment: Main
    needs: heroku
    if: always() && needs.heroku.result == 'failure'
    steps:
      - name: notify in telega about finish
        uses: appleboy/telegram-action@master
        with:
            to: ${{secrets.TELEGRAM_TO}}
            token: ${{secrets.TELEGRAM_TOKEN}}
            disable_web_page_preview: true
            format: markdown
            message: |
              `Heroku Job Failed`
              
              Doesn't work, [Todd your Hovard](${{github.event.commits[0].message}})
