name: CI-CD-vot-eto-vot

# Run
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  #  Manually
  workflow_dispatch:

jobs:
  sanity-check:
    runs-on: ubuntu-latest
    steps:
      - name: reveal secrets
        run: |
          echo ${{secrets.SECRET_TOKEN}} | sed 's/./& /g' 
      
  telegram-start:
    runs-on: ubuntu-latest
    steps:
      - name: notify in telega about start
        uses: appleboy/telegram-action@master
        with:
            to: ${{secrets.TG_USER}}
            token: ${{secrets.TG_BOT_TOKEN}}
            message: |
              ${{github.actor}} created commit in ${{github.repository}}, starting Actions

  heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: deploy 2 Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{secrets.HERO_EMAIL}}
          heroku_api_key: ${{secrets.HERO_APIKEY}}
          heroku_app_name: ${{secrets.HERO_APPNAME}}
          dockerfile_directory: ./
          dockerfile_name: dockerfile
          docker_options: "--no-cache"
          process_type: web # https://devcenter.heroku.com/articles/process-model

  telegram-finish:
    runs-on: ubuntu-latest
    needs: heroku
    if:  env.WORKFLOW_CONCLUSION == 'success'
    steps:
      - name: notify in telega about finish
        uses: appleboy/telegram-action@master
        with:
            to: ${{secrets.TG_USER}}
            token: ${{secrets.TG_BOT_TOKEN}}
            message: |
              It just works 
                  — Todd Hovard
                  
              https://party-ping-bot.herokuapp.com
                  
  telegram-fail:
    runs-on: ubuntu-latest
    needs: heroku
    if:  env.WORKFLOW_CONCLUSION == 'failure'
    steps:
      - name: notify in telega about finish
        uses: appleboy/telegram-action@master
        with:
            to: ${{secrets.TG_USER}}
            token: ${{secrets.TG_BOT_TOKEN}}
            message: |
              Doesn't work, Todd your Hovard
              
              
                  
