name: CI-CD-vot-eto-vot

# Run
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  #  Manually
  workflow_dispatch:

jobs:
  heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: deploy 2 Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HERO_EMAIL }}
          heroku_api_key: ${{ secrets.HERO_APIKEY }}
          heroku_app_name: ${{ secrets.HERO_APPNAME }}
          dockerfile_directory: ./
          dockerfile_name: dockerfile
          docker_options: "--no-cache"
          process_type: web # https://devcenter.heroku.com/articles/process-model

  telegram:
    runs-on: ubuntu-latest
    steps:
      - name: notify in telega
        uses: appleboy/telegram-action@master
        with:
            to: ${{ secrets.TG_USER }}
            token: ${{ secrets.TG_BOT_TOKEN }}
            message: |
              ${{ github.actor }} created commit ${{ github.event.commits[0].message }} in ${{ github.repository }}
              https://party-ping-bot.herokuapp.com
              It just works 
                  — Todd Hovard
